Опция интерактивного включения/выключения плагинов
oscript-library/gitsync pull request #282
Opened 2021-09-18 21:01 UTC by 240596448

Для команд включения/выключения плагинов добавил опцию --interactive с ручным выбором плагинов

@oscript-library/Collaborators - пожалуйста, проверьте изменения и прокомментируйте их

2021-09-19 07:25 UTC, artbear requested changes
есть предложения по улучшению

2021-09-19 07:25 UTC, artbear commented on packagedef
> +		.Версия("3.4.1")
Добавлена полезная фича. Предлагаю установить номер 3.5.0

2021-09-19 07:25 UTC, artbear commented on src/cmd/Классы/КомандаPluginDisable.os
> +			ИменаПлагинов = ВыборВКонсоли.Выбрать();
этот код лучше в отдельный метод выделить.

2021-09-19 07:25 UTC, artbear commented on src/cmd/Классы/КомандаPluginDisable.os
> +					ИмяПлагина = Лев(Плагин.Ключ + "              ", 15) + " - отключен";
здесь удобно разделять ключи и представление.
сделал ишуз https://github.com/240596448/cli-selector/issues/2

2021-09-19 07:25 UTC, artbear commented on src/cmd/Классы/КомандаPluginDisable.os
> +			ИменаПлагинов = ВыборВКонсоли.Выбрать();
тем более, что он продублирован в 2х классах.

2021-09-19 08:08 UTC, 240596448 commented on src/cmd/Классы/КомандаPluginDisable.os
> +			ИменаПлагинов = ВыборВКонсоли.Выбрать();
Неее.
Тут же разная логика составления меню.

2021-09-19 08:23 UTC, artbear commented on src/cmd/Классы/КомандаPluginDisable.os
> +			ИменаПлагинов = ВыборВКонсоли.Выбрать();
понятно, что совпадение кода не 100%, но код очень-очень похож
разделить логику подготовки данных и выбора
- собрать список значений - тут разная логика
- а потом перебрать этот список, добавить в меню и выбрать - а тут одна и та же

мелочь, конечно, но так легаси и появляется )

настаивать не буду, решать тебе.

2021-09-19 13:53 UTC, nixel2007 commented on packagedef
> +		.Версия("3.4.1")
Вообще не надо менять номер версии. Это делает мэйнтейнер при выпуске релиза.

2021-09-19 16:52 UTC, 240596448 commented on src/cmd/Классы/КомандаPluginDisable.os
> +			ИменаПлагинов = ВыборВКонсоли.Выбрать();
Тут совпадение кода - две строки: создать и выбрать. Остальное - это и есть подготовка данных. Что тут объединять то...? ;) 
Подготавливать данные, чтобы потом еще раз сделать то же самое?
Я категорически против повторяемости кода, но его тут и нет

2021-09-19 19:20 UTC, 240596448 commented
Если убрать вообще опцию `-i`, и опираться на логику "не заданы плагины - значит интерактив", то команда не запускается без параметров, ругается. Вероятно нужно как-то `спек` хитро задать, но я не понял как.

2021-09-20 08:41 UTC, nixel2007 commented
@240596448 потому что аргумент по умолчанию обязательный. попробуй в описании параметра добавить вызов `.Обязательный(Ложь)`

2021-09-20 18:13 UTC, artbear commented on src/cmd/Классы/КомандаPluginDisable.os
> +				ВыборВКонсоли.ДобавитьЗначениеВыбора(Плагин.Ключ, Представление, , Плагин.Значение.Включен());
3й параметр будет передан как Неопределено, а не как значение по умолчанию Ложь.

и далее он сразу попадет в реквизит Отметка.

а затем есть куча проверка Если ХХХ.Отметка Тогда

а эта проверка упадет, т.к. Неопределено нельзя юзать как булево.

2021-09-20 18:13 UTC, artbear commented on src/cmd/Классы/КомандаPluginEnable.os
> +				ВыборВКонсоли.ДобавитьЗначениеВыбора(Плагин.Ключ, Представление, , НЕ Плагин.Значение.Включен());
и здесь аналогично 3й параметр нужно явно задать.

2021-09-20 18:14 UTC, artbear commented on src/cmd/Классы/КомандаPluginDisable.os
> +			ВыборВКонсоли = Новый ВыборВКонсоли("Выберите плагины к отключению:");
в начале этого файла нет #Использовать cli-selector

а в соседнем файле есть.

2021-09-21 07:27 UTC, EvilBeaver commented on readme.md
> +* `gitsync plugins enable -i` - будет выведен список всех установленных плагинов для интерактивного выбора и активации выбранных
Мне показалось, или в чатике писали про то, что ключ -i убираем и если нет списка плагинов, то выдавать интерактив? Чем там обсуждение кончилось?

2021-09-21 20:51 UTC, 240596448 commented on src/cmd/Классы/КомандаPluginDisable.os
> +				ВыборВКонсоли.ДобавитьЗначениеВыбора(Плагин.Ключ, Представление, , Плагин.Значение.Включен());
Не понимаю, зачем задавать явно, если он по умолчанию = Ложь.
И явно задана даже типизация колонки таблицы в вызываемой библиотеке если кто-то явно передаст неопределено.

2021-09-21 21:01 UTC, 240596448 commented on readme.md
> +* `gitsync plugins enable -i` - будет выведен список всех установленных плагинов для интерактивного выбора и активации выбранных
> @240596448 потому что аргумент по умолчанию обязательный. попробуй в описании параметра добавить вызов `.Обязательный(Ложь)`

попробовал - не работает ((
`gitsync p d` без параметров падает 
_КРИТИЧНАЯОШИБКА - Ошибка чтения параметров команды_

2021-09-21 21:15 UTC, nixel2007 commented on readme.md
> +* `gitsync plugins enable -i` - будет выведен список всех установленных плагинов для интерактивного выбора и активации выбранных
А ты спек поменял соответственно?

2021-09-21 21:16 UTC, nixel2007 commented on readme.md
> +* `gitsync plugins enable -i` - будет выведен список всех установленных плагинов для интерактивного выбора и активации выбранных
Либо вообще явный спек убрать, пускай его cli генерит

2021-09-21 21:17 UTC, 240596448 commented on readme.md
> +* `gitsync plugins enable -i` - будет выведен список всех установленных плагинов для интерактивного выбора и активации выбранных
Если `Команда.Спек = ` закоментить, то можно запуститься без параметров. 
Как оно работает - отладкой не понять.

2021-09-21 21:27 UTC, khorevaa commented on readme.md
> +* `gitsync plugins enable -i` - будет выведен список всех установленных плагинов для интерактивного выбора и активации выбранных
Так вроде ж в справке либы cli все есть... и про спек с примерами

2021-09-22 15:55 UTC, 240596448 commented on readme.md
> +* `gitsync plugins enable -i` - будет выведен список всех установленных плагинов для интерактивного выбора и активации выбранных
> Так вроде ж в справке либы cli все есть... и про спек с примерами
Ну так-то конечно заработало.
Кто ж мог предполагать, что в репе есть описание ? ))
СПАСИБО!

2021-11-13 20:09 UTC, artbear commented on readme.md
> +* `gitsync plugins enable -i` - будет выведен список всех установленных плагинов для интерактивного выбора и активации выбранных
Так что в итоге решаем по 
- оставляем `gitsync plugins enable -i`
- или  ключ -i убираем и если нет списка плагинов, то выдавать интерактив
@nixel2007 @EvilBeaver @240596448

2021-11-13 20:25 UTC, merged